### ISSUE TITLE
Improve Accuracy Test

### ISSUE THREAD

**Issue by danemo01** [jacobjanak/CS410-VideaHealth#26]
The Accuracy Test was a good start for Testing to see what would be the best algorithm to get the correct Box. We want to improve on the issues so far:

- Update/Fix the missing box, and extra box algorithm
- Instead of comparing matching labels we should try to match by coordinates.

By doing this we can separate the test for accuracy for Stage 1. This would help us see how close the boxes are to the boxes to the Ground Truth.

Let's not remove the current algorithm, we can consider that once we finish Stage 1 and Stage 2.

**Comment by hayescam** [comment]
Assigned scores (0-1) using the IOU algorithm to each box compared to the ground truth, then averaged scores to get an ultimate score for each script. So far Best_Box has the highest score of ~8.9.
