### ISSUE TITLE
Implementing Metrics to evaluate our Postprocessing Tool.

### ISSUE THREAD

**Issue by danemo01** [jacobjanak/CS410-VideaHealth#37]
After the last meeting with Manuel. I've learned that we need to use specific metrics to evaluate how well our postprocessing tool is. 

For example: We can use mAP to compare how well each stage is compare to the dataset the neural network provides.

So far Thomas (Suncharn) has already implemented an F1 score, and I have used a library from github to provide us the mAP. So we're somewhat done, but we should generally discuss how we can properly implement it.

Implementation of the Precision Recall Curve:

![image](https://user-images.githubusercontent.com/9070271/115928050-7fe6b900-a453-11eb-892a-e3d0fd0a17b1.png)

-Consider looking looking at thomas's algorithm on percession_recall.py, function gt_map().
-Reimplement where each iteration of the Predicted BB, and create a Row similar to above top.
-Design and Create a Class that can save the data

**Comment by danemo01** [comment]
I've found an maP library here: https://github.com/bes-dev/mean_average_precision

**Comment by danemo01** [comment]
I found a good reading on maP: https://jonathan-hui.medium.com/map-mean-average-precision-for-object-detection-45c121a31173

**Comment by thomas-pipithkul** [comment]
https://towardsdatascience.com/map-mean-average-precision-might-confuse-you-5956f1bfa9e2
explanation of mAP

**Comment by KeLiu1234** [comment]
For the Rank table in 
https://jonathan-hui.medium.com/map-mean-average-precision-for-object-detection-45c121a31173

Precision:
rank1, predicted 1 box, and it is correct, precision is 1/1=1;
rank3, predicted 3 boxes, 2 of them are correct, precision is 2/3=0.67;
rank10, predicted 10 boxes, 5 of them are correct, precision is 5/10=0.5.

Recall:
rank1, there are 5 apples, only rank1 predicted right, Recall is 1/5=0.2;
rank3, there are 5 apples, rank1, 2 predicted right, Recall is 2/5=0.4;
rank10, there are 5 apples, rank1, 2, 6, 7, 10 predicted right, Recall is 5/5=1.

**Comment by KeLiu1234** [comment]
https://github.com/XiangZhang2/yolov3-keras

https://vignesh943628.medium.com/metrics-on-object-detection-b9fe3f1bac59

https://blog.paperspace.com/mean-average-precision/

hope it's helpful
