### ISSUE TITLE
Fix ground truth data 

### ISSUE THREAD

**Issue by mrJeffrey270** [jacobjanak/CS410-VideaHealth#43]
the file must the fix base on what happens in meeting 4 and 5 links for the meeting recording are available on discord.

**Comment by KeLiu1234** [comment]
[gt_fix_notes.txt](https://github.com/jacobjanak/CS410-VideaHealth/files/6381340/gt_fix_notes.txt)

[1_ground_truth.zip](https://github.com/jacobjanak/CS410-VideaHealth/files/6381341/1_ground_truth.zip)
